# Generated by Django 4.0.2 on 2022-02-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_api', '0002_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='description',
            new_name='channel_description',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='image',
            new_name='channel_image',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='channel_title',
        ),
    ]
