# Generated by Django 4.0.2 on 2022-02-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels_api', '0003_rename_description_channel_channel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='channels_api.category'),
        ),
    ]
