# Generated by Django 4.0.2 on 2022-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_api', '0005_alter_channel_channel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_image',
            field=models.ImageField(default='not_found.jpg', upload_to='channel'),
        ),
    ]
