# Generated by Django 4.0.2 on 2022-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_api', '0008_subcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='subcription_status',
            field=models.BooleanField(default=True),
        ),
    ]
